-- Revenue and Sales Metrics
-- 1. What is the total revenue generated by the store?
SELECT SUM(Total) AS
FROM Invoice;

-- 2. What are the top 10 best-selling tracks and albums by revenue?
-- Select 

-- Music and Artist Insights
-- 3. What genres of music are most popular?

-- Geographic Insights
-- 4. Which cities or countries generate the most revenue?

-- Transaction and Seasonal Trends
-- 5. Are there specific times of the year when sales are higher or lower?
-- 6. Which artist are popular by week, month, year?

-- Customer Insights:
-- 7. What can you tell me about our customers that are spending the most on [genre], [artist], etc.?

-- Time Based Analysis
-- 8. Advanced question(?)